# This script continues training the SFT model (models/Qwen1_5_SFT_GLM) with GRPO on the train questions.
# For every question, the model samples 16 answers, each answer is
# scored by the GSM8K reward functions, and the model is pushed toward the answers that scored above the average of
# their group. Throughout training, GRPO's own sampled validation reward and our greedy validation accuracy are
# measured on the validation set; training stops early once the validation accuracy no longer improves, and the most
# accurate model and its training curves are saved to models/Qwen1_5_SFT_GLM_GRPO/.
# Rollouts are generated by vLLM colocated on the same GPU; vLLM's FlashInfer sampler is disabled because this machine
# has no CUDA toolkit to compile it with, and torch's sampler is used instead.

import json
import os
from pathlib import Path

os.environ.setdefault("VLLM_USE_FLASHINFER_SAMPLER", "0")

from datasets import Dataset
from transformers import EarlyStoppingCallback
from trl import GRPOConfig, GRPOTrainer

from scripts.inference.prompts import XML_SYSTEM_PROMPT
from scripts.train.gsm8k_rewards import GSM8K_REWARD_FUNCTIONS
from scripts.train.validation_accuracy_callback import ValidationAccuracyCallback

SFT_MODEL_DIRECTORY = Path("models/Qwen1_5_SFT_GLM")


def main() -> None:
    train_dataset = build_grpo_dataset(Path("dataset/processed/train.json"))
    validation_dataset = build_grpo_dataset(Path("dataset/processed/val.json"))
    validation_accuracy_callback = build_validation_accuracy_callback(Path("dataset/processed/val.json"))

    grpo_trainer = build_grpo_trainer(train_dataset, validation_dataset, validation_accuracy_callback)
    grpo_trainer.train()

    output_directory = Path("models/Qwen1_5_SFT_GLM_GRPO")
    grpo_trainer.save_model(output_directory)
    save_training_curves(grpo_trainer.state.log_history, output_directory / "training_curves.json")


def build_grpo_dataset(examples_path: Path) -> Dataset:
    examples = json.loads(examples_path.read_text())
    grpo_examples = [convert_to_grpo_example(example) for example in examples]
    return Dataset.from_list(grpo_examples)


def convert_to_grpo_example(example: dict) -> dict:
    return {
        "prompt": [
            {"role": "system", "content": XML_SYSTEM_PROMPT},
            {"role": "user", "content": example["question"]},
        ],
        "ground_truth_integer_answer": example["integer_answer"],
    }


def build_validation_accuracy_callback(validation_examples_path: Path) -> ValidationAccuracyCallback:
    validation_examples = json.loads(validation_examples_path.read_text())
    questions = [validation_example["question"] for validation_example in validation_examples]
    ground_truth_integer_answers = [validation_example["integer_answer"] for validation_example in validation_examples]
    return ValidationAccuracyCallback(SFT_MODEL_DIRECTORY, questions, ground_truth_integer_answers)


def build_grpo_trainer(
    train_dataset: Dataset,
    validation_dataset: Dataset,
    validation_accuracy_callback: ValidationAccuracyCallback,
) -> GRPOTrainer:
    grpo_config = GRPOConfig(
        output_dir="models/Qwen1_5_SFT_GLM_GRPO/checkpoints",
        model_init_kwargs={"attn_implementation": "eager", "dtype": "bfloat16"},
        max_steps=200,
        per_device_train_batch_size=8,
        gradient_accumulation_steps=32,
        num_generations=16,
        temperature=1.0,
        max_completion_length=1024,
        learning_rate=5e-6,
        lr_scheduler_type="cosine",
        warmup_steps=0.1,
        adam_beta2=0.99,
        weight_decay=0.1,
        max_grad_norm=0.1,
        beta=0.0,
        loss_type="dapo",
        use_vllm=True,
        vllm_mode="colocate",
        vllm_gpu_memory_utilization=0.3,
        logging_steps=5,
        eval_strategy="steps",
        eval_steps=25,
        num_generations_eval=1,
        per_device_eval_batch_size=16,
        save_strategy="steps",
        save_steps=25,
        save_total_limit=1,
        save_only_model=True,
        load_best_model_at_end=True,
        metric_for_best_model="eval_accuracy",
        greater_is_better=True,
        report_to="none",
    )
    return GRPOTrainer(
        model=str(SFT_MODEL_DIRECTORY),
        reward_funcs=GSM8K_REWARD_FUNCTIONS,
        args=grpo_config,
        train_dataset=train_dataset,
        eval_dataset=validation_dataset,
        callbacks=[validation_accuracy_callback, EarlyStoppingCallback(early_stopping_patience=4)],
    )


def save_training_curves(log_history: list[dict[str, float]], output_path: Path) -> None:
    training_curves = {
        "train_reward": extract_curve(log_history, "reward"),
        "eval_reward": extract_curve(log_history, "eval_reward"),
        "eval_accuracy": extract_curve(log_history, "eval_accuracy"),
    }
    output_path.write_text(json.dumps(training_curves, indent=2))


def extract_curve(log_history: list[dict[str, float]], metric_name: str) -> list[dict[str, float]]:
    return [
        {"step": log_entry["step"], "value": log_entry[metric_name]}
        for log_entry in log_history
        if metric_name in log_entry
    ]


if __name__ == "__main__":
    main()
